apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: minecraft-db
spec:
  namespace: admin/dev
  mount: database/minecraft_dev
  path: creds/writer

  destination:
    create: false
    name: minecraft-db-dev
  vaultAuthRef: dev-auth